config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'


  resources :meeting_details do
    member do
      get :delete
    end
  end

  resources :users_clubs do
    member do
      get :delete
    end
  end

  resources :users do
    member do
      get :delete
    end
  end

  resources :clubs do
    member do
        get :delete
      end
  end

  resources :club_types do
    member do
        get :delete
      end
  end

  resources :meetings do
    member do
      get :delete
    end
  end



#  get 'demo/index'
#  get 'members/index'
#  get 'members/show'
#  get 'members/new'
#  get 'members/edit'
#  get 'members/delete'
#  get 'clubs/index'
#  get 'clubs/show'
#  get 'clubs/new'
#  get 'clubs/edit'
#  get 'clubs/delete'


  #get 'clubs/index'
#  get 'clubs', to: 'clubs#index'
#  get 'clubs/:id', to: 'clubs#show'
#  post 'clubs', to: 'clubs#create'

#  get 'club_status', to: 'club_status#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord

  belongs_to :club_type, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :role_rank, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.

  has_many :meetings
  has_many :meeting_details, :through => :meetings
  has_many :users_clubs
  has_many :users, :through => :users_clubs
  has_many :club_executive_users
  has_many :users_roles
  has_many :clubs_meeting_templates


  scope :sorted, lambda { order("id ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }
  # scope :daybreak, -> {joins(:users).where('users_clubs.club_id = 2')}

end

app/models/club_type.rb
class ClubType < ApplicationRecord

  has_many :clubs
  #accepts_nested_attributes_for :clubs, allow_destroy: true, reject_if: proc {|att| att['email'].blank?}

  scope :sorted, lambda { order("id ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  # scope :search, lambda {|query| where(["display_name LIKE ?", "%#{query}%"]) }

end

app/models/meeting.rb
class Meeting < ApplicationRecord

  belongs_to :meeting_type, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :meeting_status, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :club, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  has_many :meeting_details
  has_many :user_meeting_availability

  scope :sorted, lambda { order("id ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :newest_first1, lambda { order("date DESC") }
  scope :search, lambda {|query| where(["display_name LIKE ?", "%#{query}%"]) }

end

app/models/meeting_detail.rb
class MeetingDetail < ApplicationRecord

  belongs_to :meeting, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :role, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :user, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :meeting_detail_status, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.

  has_many :clubs, :through => :meetings

  scope :sorted, lambda { order("id DESC" , "sort_order ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :sort_order, lambda { order("sort_order ASC") }
  scope :search, lambda {|query| where(["discription LIKE ?", "%#{query}%"]) }

end

app/models/meeting_status.rb
class MeetingStatus < ApplicationRecord

  has_many :meetings
  accepts_nested_attributes_for :meetings, allow_destroy: true, reject_if: proc {|att| att['email'].blank?}

end

app/models/meeting_template.rb
class MeetingTemplate < ApplicationRecord

  has_many :meeting_template_details
  has_many :clubs_meeting_templates


end

app/models/meeting_type.rb
class MeetingType < ApplicationRecord

  has_many :meetings
  accepts_nested_attributes_for :meetings, allow_destroy: true, reject_if: proc {|att| att['email'].blank?}

end

app/models/role.rb
class Role < ApplicationRecord

  belongs_to :role_type, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  has_many :role_rank_detail
  has_many :users_roles
  has_many :meeting_details
  has_many :meeting_template_details
  has_many :club_executive_users

end

app/models/role_rank.rb
class RoleRank < ApplicationRecord

  has_many :role_rank_details
  has_many :clubs


end

app/models/role_rank_detail.rb
class RoleRankDetail < ApplicationRecord

  belongs_to :role_rank, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :role, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.


end

app/models/role_type.rb
class RoleType < ApplicationRecord

  has_many :roles


end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :users_roles
  has_many :users_clubs
  has_many :clubs, :through => :users_clubs
  has_many :meeting_details
  has_many :user_meeting_availability
  has_many :club_executive_users


  scope :sorted, lambda { order("id ASC") }
  scope :first_name, lambda { order("first_name ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :search, lambda {|query| where(["display_name LIKE ?", "%#{query}%"]) }

  scope :active, -> { joins(:users_clubs).where(:users_clubs => {:user_type_id => 1}) }

end

app/models/user_type.rb
class UserType < ApplicationRecord

  has_many :users_clubs


end

app/models/users_club.rb
class UsersClub < ApplicationRecord
  belongs_to :club, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :user, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :user_type, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.

  scope :sorted, lambda { order("comments ASC") }
  scope :first_name, lambda { joins(:user).merge(User.first_name) }
  scope :active_first, lambda { order("user_type_id ASC") }
  scope :newest_first1, lambda { order("date DESC") }
  scope :search, lambda {|query| where(["display_name LIKE ?", "%#{query}%"]) }

end

app/models/users_role.rb
class UsersRole < ApplicationRecord
  belongs_to :user, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :role, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :club, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController

  layout 'bootstrap'
  # before_action :confirm_logged_in

  def index
    @clubs = Club.sorted
    @users = UsersClub
  end

  def show
    @club = Club.find(params[:id])
    @users = User.joins(:clubs).where(:users_clubs => {:club_id => 1, :user_type_id => 1})
  end

  def new
    @club = Club.new({:display_name => 'Default'})
  end

  def create
    @club = Club.new(club_params)
    if @club.save
      flash[:notice] = "Club '#{@club.name}' created successfully"
      redirect_to(clubs_path)
    else
      render('new')
    end
  end

  def edit
    @club = Club.find(params[:id])
  end

  def update
    @club = Club.find(params[:id])
    if @club.update_attributes(club_params)
      flash[:notice] = "Club '#{@club.name}' updated successfully"
      redirect_to(club_path(@club))
    else
      render('edit')
    end
  end

  def delete
    @club = Club.find(params[:id])
  end

  def destroy
    @club = Club.find(params[:id])
    @club.destroy
    flash[:notice] = "Club '#{@club.name}' deleted successfully"
    redirect_to(clubs_path)
  end

  private
    def club_params
      params.require(:club).permit(:name, :description, :city, :country, :club_type_id, :start_date, :end_date, :address, :district, :division, :area, :registration_number, :website, :email, :mission, :facebook, :display_name, :logo, :created_at, :updated_at)
    end

end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/club_status_helper.rb
module ClubStatusHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clubs/delete.html.erb
<% @page_title = "Delete Club" %>

<h2>Delete Club</h2>
<%= link_to("<< Back to List", clubs_path, :class => 'back-link') %>
<%= form_for(@club, :method => 'delete') do |f| %>
  <p>Are you sure you want to permanently delete this club?</p>
  <p class="reference-name"><%= f.object.name %></p>
  <div class="form-buttons">
    <%= f.submit("Delete Club") %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<% @page_title = "Update Club" %>

<h2>Update Club</h2>
<%= link_to("<< Back to List", clubs_path, :class => 'back-link') %>
<%= simple_form_for(@club) do |f| %>
  <%= f.input :id %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :city %>
  <%= f.input :country %>
  <%= f.association :club_type, label_method: :name, include_blank: true, prompt: "Choose a Club Type" %>
  <%= f.input :start_date %>
  <%= f.input :end_date, include_blank: true %>
  <%= f.input :address %>
  <%= f.input :district %>
  <%= f.input :division %>
  <%= f.input :area %>
  <%= f.input :registration_number %>
  <%= f.input :website %>
  <%= f.input :email %>
  <%= f.input :mission %>
  <%= f.input :facebook %>
  <%= f.input :display_name %>
  <%= f.input :logo %>
  <%= f.button :submit %>
<% end %>

app/views/clubs/index.html.erb
<% @page_title = "All Clubs" %>

<h2>Clubs</h2>
<%= link_to("Add New Club", new_club_path, :class => 'action new') %>

<table class="table table-striped">
  <tr class="header">
    <th>#</th>
    <th>Club</th>
    <th># of Users</th>
    <th>Actions</th>
  </tr>


  <% @clubs.each do |club| %>
    <tr>
      <td><%= club.id %></td>
      <td><%= club.name %></td>
      <td><%= club.users_clubs.size %></td>
      <td>
        <%= link_to("View Members", users_clubs_path(:club_id => club.id), :class => 'action show') %>
        <%= link_to("Show", club_path(club), :class => 'action show') %>
        <%= link_to("Edit", edit_club_path(club), :class => 'action edit') %>
        <%= link_to("Delete", delete_club_path(club), :class => 'action delete') %>
      </td>
    </tr>
  <% end %>

app/views/clubs/new.html.erb
<% @page_title = "New Club" %>

<h2>New Club</h2>
<%= link_to("<< Back to List", clubs_path, :class => 'back-link') %>
<%= simple_form_for(@club) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :city %>
  <%= f.input :country %>
  <%= f.association :club_type, label_method: :name, include_blank: true, prompt: "Choose a Club Type" %>
  <%= f.input :start_date %>
  <%= f.input :end_date, include_blank: true %>
  <%= f.input :address %>
  <%= f.input :district %>
  <%= f.input :division %>
  <%= f.input :area %>
  <%= f.input :registration_number %>
  <%= f.input :website %>
  <%= f.input :email %>
  <%= f.input :mission %>
  <%= f.input :facebook %>
  <%= f.input :display_name %>
  <%= f.input :logo %>
  <%= f.button :submit %>
<% end %>

app/views/clubs/show.html.erb
<% @page_title = "Show Clubs" %>

<h2>Club Details</h2>
<%= link_to("<< Back to List", clubs_path, :class => 'back-link') %>
<%= simple_form_for(@club) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :city %>
  <%= f.input :country %>
  <%= f.association :club_type, label_method: :name, include_blank: true, prompt: "Choose a Club Type" %>
  <%= f.input :start_date %>
  <%= f.input :end_date, include_blank: true %>
  <%= f.input :address %>
  <%= f.input :district %>
  <%= f.input :division %>
  <%= f.input :area %>
  <%= f.input :registration_number %>
  <%= f.input :website %>
  <%= f.input :email %>
  <%= f.input :mission %>
  <%= f.input :facebook %>
  <%= f.input :display_name %>
  <%= f.input :logo %>
  <%= f.input :created_at %>
  <%= f.input :updated_at %>
<% end %>

</n/n>

<table class="table table-striped">
  <tr class="header">
    <th>#</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Actions</th>
  </tr>


  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td>      </td>
    </tr>
  <% end %>