config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'


  resources :meeting_details do
    member do
      get :delete
    end
  end

  resources :users_clubs do
    member do
      get :delete
    end
  end

  resources :users do
    member do
      get :delete
    end
  end

  resources :clubs do
    member do
        get :delete
      end
  end

  resources :club_types do
    member do
        get :delete
      end
  end

  resources :meetings do
    member do
      get :delete
    end
  end



#  get 'demo/index'
#  get 'members/index'
#  get 'members/show'
#  get 'members/new'
#  get 'members/edit'
#  get 'members/delete'
#  get 'clubs/index'
#  get 'clubs/show'
#  get 'clubs/new'
#  get 'clubs/edit'
#  get 'clubs/delete'


  #get 'clubs/index'
#  get 'clubs', to: 'clubs#index'
#  get 'clubs/:id', to: 'clubs#show'
#  post 'clubs', to: 'clubs#create'

#  get 'club_status', to: 'club_status#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord

  belongs_to :club_type, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :role_rank, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.

  has_many :meetings
  has_many :meeting_details, :through => :meetings
  has_many :users_clubs
  has_many :users, :through => :users_clubs
  has_many :club_executive_users
  has_many :users_roles
  has_many :clubs_meeting_templates


  scope :sorted, lambda { order("id ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :search, lambda {|query| where(["name LIKE ?", "%#{query}%"]) }
  # scope :daybreak, -> {joins(:users).where('users_clubs.club_id = 2')}

end

app/models/club_type.rb
class ClubType < ApplicationRecord

  has_many :clubs
  #accepts_nested_attributes_for :clubs, allow_destroy: true, reject_if: proc {|att| att['email'].blank?}

  scope :sorted, lambda { order("id ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  # scope :search, lambda {|query| where(["display_name LIKE ?", "%#{query}%"]) }

end

app/models/meeting.rb
class Meeting < ApplicationRecord

  belongs_to :meeting_type, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :meeting_status, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :club, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  has_many :meeting_details
  has_many :user_meeting_availability

  scope :sorted, lambda { order("id ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :newest_first1, lambda { order("date DESC") }
  scope :search, lambda {|query| where(["display_name LIKE ?", "%#{query}%"]) }

end

app/models/meeting_detail.rb
class MeetingDetail < ApplicationRecord

  belongs_to :meeting, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :role, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :user, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :meeting_detail_status, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.

  has_many :clubs, :through => :meetings

  scope :sorted, lambda { order("id DESC" , "sort_order ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :sort_order, lambda { order("sort_order ASC") }
  scope :search, lambda {|query| where(["discription LIKE ?", "%#{query}%"]) }

end

app/models/meeting_status.rb
class MeetingStatus < ApplicationRecord

  has_many :meetings
  accepts_nested_attributes_for :meetings, allow_destroy: true, reject_if: proc {|att| att['email'].blank?}

end

app/models/meeting_template.rb
class MeetingTemplate < ApplicationRecord

  has_many :meeting_template_details
  has_many :clubs_meeting_templates


end

app/models/meeting_type.rb
class MeetingType < ApplicationRecord

  has_many :meetings
  accepts_nested_attributes_for :meetings, allow_destroy: true, reject_if: proc {|att| att['email'].blank?}

end

app/models/role.rb
class Role < ApplicationRecord

  belongs_to :role_type, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  has_many :role_rank_detail
  has_many :users_roles
  has_many :meeting_details
  has_many :meeting_template_details
  has_many :club_executive_users

end

app/models/role_rank.rb
class RoleRank < ApplicationRecord

  has_many :role_rank_details
  has_many :clubs


end

app/models/role_rank_detail.rb
class RoleRankDetail < ApplicationRecord

  belongs_to :role_rank, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :role, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.


end

app/models/role_type.rb
class RoleType < ApplicationRecord

  has_many :roles


end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :users_roles
  has_many :users_clubs
  has_many :clubs, :through => :users_clubs
  has_many :meeting_details
  has_many :user_meeting_availability
  has_many :club_executive_users


  scope :sorted, lambda { order("id ASC") }
  scope :first_name, lambda { order("first_name ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :search, lambda {|query| where(["display_name LIKE ?", "%#{query}%"]) }

  scope :active, -> { joins(:users_clubs).where(:users_clubs => {:user_type_id => 1}) }

end

app/models/user_type.rb
class UserType < ApplicationRecord

  has_many :users_clubs


end

app/models/users_club.rb
class UsersClub < ApplicationRecord
  belongs_to :club, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :user, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :user_type, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.

  scope :sorted, lambda { order("comments ASC") }
  scope :first_name, lambda { joins(:user).merge(User.first_name) }
  scope :active_first, lambda { order("user_type_id ASC") }
  scope :newest_first1, lambda { order("date DESC") }
  scope :search, lambda {|query| where(["display_name LIKE ?", "%#{query}%"]) }

end

app/models/users_role.rb
class UsersRole < ApplicationRecord
  belongs_to :user, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :role, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :club, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController

  layout 'bootstrap'

  def index
    @meetings = Meeting.joins(:club, :meeting_type, :meeting_status).newest_first1

  end

  def show
    @meeting = Meeting.joins(:club, :meeting_type, :meeting_status).find(params[:id])
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(user_params)
    if @meeting.save
      flash[:notice] = "Meeting '#{@meeting.theme}' created successfully"
      redirect_to(meetings_path)
    else
      render('new')
    end
  end

  def edit
    @meeting = Meeting.find(params[:id])
  end

  def update
    @meeting = Meeting.find(params[:id])
    if @meeting.update_attributes(user_params)
      flash[:notice] = "Meeting '#{@meeting.theme}' updated successfully"
      redirect_to(meeting_path(@meeting))
    else
      render('edit')
    end
  end

  def delete
    @meeting = Meeting.find(params[:id])
  end


  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    flash[:notice] = "Meeting '#{@meeting.theme}' deleted successfully"
    redirect_to(meetings_path)
  end

  private
    def user_params
      params.require(:meeting).permit(:meeting_type_id, :club_id, :meeting_status_id, :location, :date, :theme, :address, :arrival_comments, :created_at, :updated_at)
    end


end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/club_status_helper.rb
module ClubStatusHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/users_clubs_helper.rb
module UsersClubsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/meetings/delete.html.erb
<% @page_title = "Delete Meeting" %>

<h2>Delete Meeting</h2>
<%= link_to("<< Back to List", meetings_path, :class => 'back-link') %>
  <%= form_for(@meeting, :method => 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this meeting?</p>
    <p class="reference-name"><%= f.object.theme %></p>
    <div class="form-buttons">
      <%= f.submit("Delete meeting") %>
    </div>
  <% end %>

app/views/meetings/edit.html.erb
<% @page_title = "Update Meeting" %>

<h2>Update Meeting</h2>
<%= link_to("<< Back to List", meetings_path, :class => 'back-link') %>
<%= simple_form_for(@meeting, html: { class: 'form-vertical' }) do |f| %>
<%= f.association :meeting_type, label_method: :name, include_blank: true, prompt: "Choose a Meeting Type" %>
<%= f.association :meeting_status, label_method: :name, include_blank: true, prompt: "Choose a meeting status" %>
<%= f.association :club, label_method: :name, include_blank: true, prompt: "Choose a Club" %>
<%= f.input :location %>
<%= f.input :date %>
<%= f.input :theme %>
<%= f.input :address %>
<%= f.input :arrival_comments %>
<%= f.button :submit %>
<% end %>

app/views/meetings/index.html.erb
<% @page_title = "All Meetings" %>

<h2>Meetings</h2>
<%= link_to("Add New Meeting", new_meeting_path, :class => 'action new') %>

<table class="table table-striped">
  <tr class="header">
    <th>Meeting ID</th>
    <th>Club</th>
    <th>Type</th>
    <th>Meeting Status</th>
    <th>Date</th>
    <th>Theme</th>
    <th>Actions</th>
  </tr>

  <% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.id %></td>
    <td><%= meeting.club.name %></td>
    <td><%= meeting.meeting_type.name %></td>
    <td><%= meeting.meeting_status.name %></td>
    <td><%= meeting.date.strftime("%d %b - %I:%M%p") %></td>
    <td><%= meeting.theme %></td>
    <td >
      <%= link_to("Show", meeting_path(meeting), :class => 'action show') %>
      <%= link_to("Edit", edit_meeting_path(meeting), :class => 'action edit') %>
      <%= link_to("Delete", delete_meeting_path(meeting), :class => 'action delete') %>
      <%= link_to("Index", {:controller => 'meeting_details', :action => 'index', :meeting_id => meeting.id})  %>

 
    </td>
  </tr>

  <% end %>

app/views/meetings/new.html.erb
<% @page_title = "New Meeting" %>

<h2>Create Meeting</h2>
<%= link_to("<< Back to List", meetings_path, :class => 'back-link') %>
<%= simple_form_for(@meeting, html: { class: 'form-vertical' }) do |f| %>
<%= f.association :meeting_type, label_method: :name, include_blank: true, prompt: "Choose a Meeting Type" %>
<%= f.association :meeting_status, label_method: :name, include_blank: true, prompt: "Choose a meeting status" %>
<%= f.association :club, label_method: :name, include_blank: true, prompt: "Choose a Club" %>
<%= f.input :location %>
<%= f.input :date %>
<%= f.input :theme %>
<%= f.input :address %>
<%= f.input :arrival_comments %>
<%= f.button :submit %>
<% end %>

app/views/meetings/show.html.erb
<% @page_title = "Show Meeting" %>

<h2>Show Meetings</h2>
<%= link_to("<< Back to List", meetings_path, :class => 'back-link') %>
<%= simple_form_for(@meeting, html: { class: 'form-vertical' }) do |f| %>
<%= f.association :meeting_type, label_method: :name, include_blank: true, prompt: "Choose a Meeting Type" %>
<%= f.association :meeting_status, label_method: :name, include_blank: true, prompt: "Choose a meeting status" %>
<%= f.association :club, label_method: :name, include_blank: true, prompt: "Choose a Club" %>
<%= f.input :location %>
<%= f.input :date %>
<%= f.input :theme %>
<%= f.input :address %>
<%= f.input :arrival_comments %>
<%= f.input :created_at %>
<%= f.input :updated_at %>
<% end %>