config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'


  resources :meeting_details do
    member do
      get :delete
    end
  end

  resources :users_clubs do
    member do
      get :delete
    end
  end

  resources :users do
    member do
      get :delete
    end
  end

  resources :clubs do
    member do
        get :delete
      end
  end

  resources :club_types do
    member do
        get :delete
      end
  end

  resources :meetings do
    member do
      get :delete
    end
  end



#  get 'demo/index'
#  get 'members/index'
#  get 'members/show'
#  get 'members/new'
#  get 'members/edit'
#  get 'members/delete'
#  get 'clubs/index'
#  get 'clubs/show'
#  get 'clubs/new'
#  get 'clubs/edit'
#  get 'clubs/delete'


  #get 'clubs/index'
#  get 'clubs', to: 'clubs#index'
#  get 'clubs/:id', to: 'clubs#show'
#  post 'clubs', to: 'clubs#create'

#  get 'club_status', to: 'club_status#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting_detail.rb
class MeetingDetail < ApplicationRecord

  belongs_to :meeting, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :role, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :user, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :meeting_detail_status, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.

  has_many :clubs, :through => :meetings

  scope :sorted, lambda { order("id DESC" , "sort_order ASC") }
  scope :newest_first, lambda { order("created_at DESC") }
  scope :sort_order, lambda { order("sort_order ASC") }
  scope :search, lambda {|query| where(["discription LIKE ?", "%#{query}%"]) }

end

app/controllers/meeting_details_controller.rb
class MeetingDetailsController < ApplicationController

  # acts_as_list :scope => :meeting_id
  layout 'bootstrap'

  def index
    ## Index is filtered down by clicking on Index link from meetings and focused just on a specific meeting.
    ## IF
    if
      params[:newrow].present?
      @meeting_id = params[:meeting_id]
      @new_meeting_entry = MeetingDetail.new(:meeting_id => @meeting_id, :role_id => '29', :user_id => '73', :meeting_detail_status_id => '4')
      @new_meeting_entry.save
      @meeting_details = MeetingDetail.joins(:meeting, :user, :role, :meeting_detail_status).where(:meeting_details => {:meeting_id => @meeting_id}).sort_order

      elsif
         params[:meeting_id].present?
        @meeting_id = params[:meeting_id]
        @meeting_details = MeetingDetail.joins(:meeting, :user, :role, :meeting_detail_status).where(:meeting_details => {:meeting_id => @meeting_id}).sort_order

      else
        @meeting_details = MeetingDetail.joins(:meeting, :user, :role, :meeting_detail_status).sorted
      end

    # Information below is for the PDF file generation.
    @meeting_id = params[:meeting_id]
    @meeting_details = MeetingDetail.joins(:meeting, :user, :role, :meeting_detail_status).where(:meeting_details => {:meeting_id => @meeting_id}).sort_order
    respond_to do |format|
      format.html
      format.pdf do
        pdf = MeetingDetailsPdf.new(@meeting_details, @meeting_id)
        send_data pdf.render, filename: "meetingdetails_#{@meeting_id}.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  def show
    @meeting_detail = MeetingDetail.find(params[:id])
  end


  def new
    @meeting_detail = MeetingDetail.new
  end

  def create
    @meeting_detail = MeetingDetail.new(user_params)
    if @meeting_detail.save
      flash[:notice] = "Meeting '#{@meeting_detail.id}' created successfully"
      redirect_to(meetings_path)
    else
      render('new')
    end
  end

  def edit
    @meeting_details = MeetingDetail.joins(:meeting, :user, :role, :meeting_detail_status).where(:meeting_details => {:meeting_id => '134'}).sort_order
  end

  def update
    @meeting_detail = MeetingDetail.find(params[:id])
    if @meeting_detail.update_attributes(user_params)
      flash[:notice] = "Meeting '#{@meeting_detail.id}' updated successfully"
      redirect_to(meeting_path(@meeting_detail))
    else
      render('edit')
    end
  end

  def delete
    @eeting_detail = MeetingDetail.find(params[:id])
  end

  def destroy
    @meeting_detail = MeetingDetail.find(params[:id])
    @meeting_detail.destroy
    flash[:notice] = "Meeting '#{@meeting_detail.id}' deleted successfully"
    redirect_to(meetings_path)
  end

  private
    def user_params
      params.require(:meeting_detail).permit(:meeting_type_id, :club_id, :meeting_id, :meeting_status_id, :location, :date, :theme, :address, :arrival_comments, :created_at, :updated_at)
    end


end

app/helpers/meeting_details_helper.rb
module MeetingDetailsHelper
end

app/views/meeting_details/delete.html.erb
<h1>MeetingDetails#delete</h1>
<p>Find me in app/views/meeting_details/delete.html.erb</p>

app/views/meeting_details/edit.html.erb
<% @page_title = "Edit MeetingDetails" %>

<h2>Edit MeetingDetails</h2>

<%= link_to("<< Back to Meetings", meetings_path, :class => 'back-link') %>

<%= @meeting_details.each do |g| %>

<div class="form-inline">
  <%= simple_form_for(g) do |f| %>
    <%= f.association :role, label_method: :name, include_blank: true, label: false %>
    <%= f.association :user, label_method: :display_name, include_blank: true, label: false %>
    <%= f.association :meeting_detail_status, label_method: :name, include_blank: true, label: false %>
    <%= f.input :sort_order, placeholder: 'sort order', label: false %>
    <%= f.input :duration_from, placeholder: 'Min time', label: false %>
    <%= f.input :duration_to, placeholder: 'Max time', label: false %>
    <%= f.input :description, placeholder: 'Description', label: false %>
    <%= f.input :comments, placeholder: 'Comments', label: false %>
    <%= f.button :submit %>
  <% end %>
</div>

<% end %>

app/views/meeting_details/edit0.html.erb
<% @page_title = "Edit MeetingDetails" %>

<h2>Edit MeetingDetails</h2>

<%= link_to("<< Back to Meetings", meetings_path, :class => 'back-link') %>

<%= @meeting_details.each do |g| %>

<div class="form-inline">
  <%= simple_form_for(g) do |f| %>
    <%= f.association :role, label_method: :name, include_blank: true, disabled: false %>
    <%= f.association :user, label_method: :display_name, include_blank: true %>
    <%= f.association :meeting_detail_status, label_method: :name, include_blank: true %>
    <%= f.input :sort_order, placeholder: 'sort order' %>
    <%= f.input :duration_from, placeholder: 'Min time' %>
    <%= f.input :duration_to, placeholder: 'Max time' %>
    <%= f.input :description, placeholder: 'Description' %>
    <%= f.input :comments, placeholder: 'Comments' %>
    <%= f.button :submit %>
  <% end %>
</div>

<% end %>

app/views/meeting_details/index.html.erb
<% @page_title = "All Meeting Details" %>

<h2>Meeting Details</h2>
<%= link_to("Add New Meeting Detail", meeting_details_path(:meeting_id => @meeting_id, :newrow => '1'), :class => 'action index')  %>
</br>
<%= link_to "PDF File", meeting_details_path(:meeting_id => @meeting_id, format: 'pdf') %>

<table class="table table-striped">
  <tr class="header">
    <th>ID</th>
    <th>Date</th>
    <th>Theme</th>
    <th>Role</th>
    <th>User</th>
    <th>Meeting Detail Status</th>
    <th>Sort Order</th>
    <th>Duration From</th>
    <th>Duration To</th>
    <th>Description</th>
    <th>Comments</th>
    <th>Actions</th>
  </tr>

  <% @meeting_details.each do |f| %>
  <tr>
    <td><%= f.meeting.id %></td>
    <td><%= f.meeting.date.strftime("%d %b - %I:%M%p") %></td>
    <td><%= f.meeting.theme %></td>
    <td><%= f.role.name %></td>
    <td><%= f.user.display_name %></td>
    <td><%= f.meeting_detail_status.name %></td>
    <td><%= f.sort_order %></td>
    <td><%= f.duration_from %></td>
    <td><%= f.duration_to %></td>
    <td><%= f.description %></td>
    <td><%= f.comments %></td>
    <td >
      <%= link_to("Show", meeting_detail_path(f), :class => 'action show') %>
      <%= link_to("Edit", edit_meeting_detail_path(f, :hello=>1), :class => 'action edit') %>
      <%= link_to("Delete", delete_meeting_detail_path(f), :class => 'action delete') %>
    </td>
  </tr>

  <% end %>

app/views/meeting_details/new.html.erb
<h1>MeetingDetails#new</h1>
<p>Find me in app/views/meeting_details/new.html.erb</p>

app/views/meeting_details/show.html.erb
<h1>MeetingDetails#show</h1>
<p>Find me in app/views/meeting_details/show.html.erb</p>