config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'


  resources :meeting_details do
    member do
      get :delete
    end
  end

  resources :users_clubs do
    member do
      get :delete
    end
  end

  resources :users do
    member do
      get :delete
    end
  end

  resources :clubs do
    member do
        get :delete
      end
  end

  resources :club_types do
    member do
        get :delete
      end
  end

  resources :meetings do
    member do
      get :delete
    end
  end



#  get 'demo/index'
#  get 'members/index'
#  get 'members/show'
#  get 'members/new'
#  get 'members/edit'
#  get 'members/delete'
#  get 'clubs/index'
#  get 'clubs/show'
#  get 'clubs/new'
#  get 'clubs/edit'
#  get 'clubs/delete'


  #get 'clubs/index'
#  get 'clubs', to: 'clubs#index'
#  get 'clubs/:id', to: 'clubs#show'
#  post 'clubs', to: 'clubs#create'

#  get 'club_status', to: 'club_status#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/users_club.rb
class UsersClub < ApplicationRecord
  belongs_to :club, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :user, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.
  belongs_to :user_type, optional: true #alae001 - need to remove optional statement to ensure rule is enforced.

  scope :sorted, lambda { order("comments ASC") }
  scope :first_name, lambda { joins(:user).merge(User.first_name) }
  scope :active_first, lambda { order("user_type_id ASC") }
  scope :newest_first1, lambda { order("date DESC") }
  scope :search, lambda {|query| where(["display_name LIKE ?", "%#{query}%"]) }

end

app/controllers/users_clubs_controller.rb
class UsersClubsController < ApplicationController

  layout 'bootstrap'

  before_action :find_club

  def index
    @users_clubs = @club.users_clubs.active_first.first_name

  end

  def show
    @users_club = UsersClub.joins(:club, :user, :user_type).find(params[:id])
  end

  def new
    @users_club = UsersClub.new(:club_id => @club.id)
  end

  def create
    @users_club = UsersClub.new(user_params)
    if @users_club.save
      flash[:notice] = "UsersClub '#{@users_club.user_id}' created successfully"
      redirect_to(users_clubs_path(:club_id => @club.id))
    else
      render('new')
    end
  end

  def edit
    @users_club = UsersClub.find(params[:id])
  end

  def update
    @users_club = UsersClub.find(params[:id])
    if @users_club.update_attributes(user_params)
      flash[:notice] = "UsersClub '#{@users_club.user_id}' updated successfully"
      redirect_to(users_club_path(@users_club, :club_id => @club.id))
    else
      render('edit')
    end
  end

  def delete
    @users_club = UsersClub.find(params[:id])
  end


  def destroy
    @users_club = UsersClub.find(params[:id])
    @users_club.destroy
    flash[:notice] = "UsersClub '#{@users_club.user_id}' deleted successfully"
    redirect_to(users_clubs_path(:club_id => @club.id))
  end

  private
    def user_params
      params.require(:users_club).permit(:user_id, :club_id, :user_type_id, :start_date, :end_date, :comments, :created_at, :updated_at)
    end

  def find_club
    @club = Club.find(params[:club_id])
  end

end

app/helpers/users_clubs_helper.rb
module UsersClubsHelper
end

app/views/users_clubs/delete.html.erb
<h1>UsersClubs#delete</h1>
<p>Find me in app/views/users_clubs/delete.html.erb</p>

app/views/users_clubs/edit.html.erb
<% @page_title = "Edit UsersCub" %>

<h2>Edit UserClub</h2>
<%= link_to("<< Back to List", users_clubs_path(:club_id => @club.id), :class => 'back-link') %>

<%= simple_form_for(@users_club, url: users_club_path(@club, :club_id => @club.id), html: { class: 'form-vertical' }) do |f| %>
<%= f.association :user, label_method: :display_name, include_blank: true, prompt: "Choose a User" %>
<%= f.association :club, label_method: :name, include_blank: true, prompt: "Choose a Club" %>
<%= f.association :user_type, label_method: :name, include_blank: true, prompt: "Choose a User Type" %>
<%= f.input :start_date %>
<%= f.input :end_date %>
<%= f.input :comments %>
<%= f.button :submit %>
<% end %>

app/views/users_clubs/index.html.erb
<% @page_title = "All UsersClubs" %>

<%= link_to("<< Back to Clubs", clubs_path, :class => 'bank-link') %>

<h2>Users Clubs</h2>
<%= link_to("Add New UsersClubs", new_users_club_path(:club_id => @club.id), :class => 'action new') %>

<table class="table table-striped">
  <tr class="header">
    <th>User</th>
    <th>Club</th>
    <th>User Type</th>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Comments</th>
    <th>Actions</th>
  </tr>

  <% @users_clubs.each do |f| %>
  <tr>
    <td><%= f.user.display_name %></td>
    <td><%= f.club.name %></td>
    <td><%= f.user_type.name %></td>
    <td><%= f.start_date %></td>
    <td><%= f.end_date %></td>
    <td><%= f.comments %></td>

    <td >
      <%= link_to("Show", users_club_path(f, :club_id => @club.id), :class => 'action show') %>
      <%= link_to("Edit", edit_users_club_path(f, :club_id => @club.id), :class => 'action edit') %>
      <%= link_to("Delete", delete_users_club_path(f, :club_id => @club.id), :class => 'action delete') %>
    </td>
  </tr>

  <% end %>

app/views/users_clubs/new.html.erb
<% @page_title = "New UsersCub" %>

<h2>Create UserClub</h2>
<%= link_to("<< Back to List", users_clubs_path(:club_id => @club.id), :class => 'back-link') %>

<%= simple_form_for(@users_club, url: users_clubs_path(:club_id => @club.id), html: { class: 'form-vertical' }) do |f| %>
<%= f.association :user, label_method: :display_name, include_blank: true, prompt: "Choose a User" %>
<%= f.association :club, label_method: :name, include_blank: true, prompt: "Choose a Club" %>
<%= f.association :user_type, label_method: :name, include_blank: true, prompt: "Choose a User Type" %>
<%= f.input :start_date %>
<%= f.input :end_date %>
<%= f.input :comments %>
<%= f.button :submit %>
<% end %>

app/views/users_clubs/show.html.erb
<% @page_title = "Show Users Clubs" %>

<h2>Show Users Clubs</h2>
<%= link_to("<< Back to List", users_clubs_path(:club_id => @club.id), :class => 'back-link') %>
<%= simple_form_for(@users_club, html: { class: 'form-vertical' }) do |f| %>
<%= f.association :user, label_method: :display_name, include_blank: true, prompt: "Choose a User" %>
<%= f.association :club, label_method: :name, include_blank: true, prompt: "Choose a Club" %>
<%= f.association :user_type, label_method: :name, include_blank: true, prompt: "Choose a User Type" %>
<%= f.input :start_date %>
<%= f.input :end_date %>
<%= f.input :comments %>
<% end %>